
# Estructuras de Datos Numpy 🙂

## 📙📗📔Bibliotecas

In [3]:
%pylab inline
from numpy import array

Populating the interactive namespace from numpy and matplotlib


# NDARRAY

Formación multidimensional homogenea, todos los elementos son del mismo tipo



## Creación de un ndarray de una dimensión

Desde una lista de python

In [3]:
a = array([1,2,3,4])

In [4]:
a

array([1, 2, 3, 4])

In [5]:
type(a)

numpy.ndarray

Desde una tupla de python


In [5]:
b = array((1.1,2.2,3.3,4))

In [6]:
b

array([ 1.1,  2.2,  3.3,  4. ])

In [7]:
type(b)

numpy.ndarray

## Creación de un narray de 2 dimensiones


In [10]:
a2= array([[1,2,3],[4,5,6]])

In [11]:
a2


array([[1, 2, 3],
       [4, 5, 6]])

### Atributos más importantes

ndarray.ndim => numero de dimensiones(también llamado rank)

In [12]:
a2.ndim

2

ndarray.shape => tupla que indica las dimensiones de la formación.

El tamaño de la formación en cada dimensión (n,m)=> n lineas y m columnas

In [13]:
a2.shape

(2, 3)

ndarray.size => número total de elementos en la formación

In [14]:
a2.size

6

ndarray.dtype => tipo de elementos en la formación

In [15]:
a2.dtype

dtype('int32')



## Creación de formaciones de n-dimensiones😄

De la misma forma que se transforma listas de listas en formaciones de 2 dimensiones, se puede transformar listas de listas en ndimensiones y asi sucesivamente

In [16]:
a3 = array([[[[1, 2], [3, 4]], [[5, 6], [7, 8]]],[[[9, 10], [11, 12]], [[13, 14], [15,16]]]])

In [17]:
a3

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]]],


       [[[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]]])

In [18]:
a3.size

16

In [19]:
a3.ndim

4

In [20]:
a3.shape

(2, 2, 2, 2)


## Generación Automática de Elementos

Formación rellena con ceros zeros(tupla con dimensiones) => creará una formación con las dimensiones introducidas en su argumento (una tupla)


In [22]:
z= zeros((4,5))

In [23]:
z

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

Formación rellena con unos ones(tupla con dimensiones) => creará una formación con unos


In [24]:
o = ones((4,5))

In [25]:
o

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

Formación rellena con elementos vacíos empty(tupla con dimensiones) => creará una formación con elementos vacíos

In [27]:
e = empty((2,3))

In [28]:
e

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

Formación rellena secuencialmente arange(de, a, incremento) => crea una formación de una dimensión con una secuencia de números


In [32]:
s = arange(5,10,1)

In [33]:
s

array([5, 6, 7, 8, 9])

linspace(de, a, número de elementos) => misma funcionalidad pero indicando el número de elementos en lugar del incremento. Más adecuada para tratar con números decimales


In [34]:
s2 = linspace(5.5, 10, 20)


In [35]:
s2

array([  5.5       ,   5.73684211,   5.97368421,   6.21052632,
         6.44736842,   6.68421053,   6.92105263,   7.15789474,
         7.39473684,   7.63157895,   7.86842105,   8.10526316,
         8.34210526,   8.57894737,   8.81578947,   9.05263158,
         9.28947368,   9.52631579,   9.76315789,  10.        ])

Formación rellena aleatoriamente random.random(tupla con dimensiones) => crea una formación con las dimensiones introducidas y la rellena con números aleatorios de la distribución [0, 1)


In [36]:
 r = random.random( (2, 3) )


In [37]:
r

array([[ 0.02831921,  0.79795985,  0.25353923],
       [ 0.58552862,  0.32999149,  0.7537629 ]])